### ISSUE TITLE
I am getting [object],[object] on points

### ISSUE THREAD

**Issue by sunnixx** [NathanEpstein/kmeans.js#4]
`[ { centroid: [ 10.5, 11 ], points: [ [Object], [Object] ] },
  { centroid: [ -9.5, 10.5 ], points: [ [Object], [Object] ] },
  { centroid: [ 0.3333333333333333, 0.3333333333333333 ],
    points: [ [Object], [Object], [Object] ] } ]`
How can I remove this [Object] in the points

**Comment by TheInvoker** [comment]
you are printing the string version of an array. Do this
console.log(JSON.stringify(res), null, '\t');

if you console.log([2,3]), it gives you [Object] because you are printing the array not the contents of the array.

**Comment by sunnixx** [comment]
@TheInvoker Thanks, I stopped working on this but I think this might be helpful for others as well.
